# Generated by Django 4.2.21 on 2025-05-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('m_descri', models.CharField(max_length=255)),
                ('m_robots', models.CharField(max_length=255)),
                ('m_handF', models.CharField(max_length=255, null=True)),
                ('m_mobileOp', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
