name: Deploy Django to AWS

on:
  push:
    branches:
      - main  # o tu rama de producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        env:
          DJANGO_SETTINGS_MODULE: myproject.settings.prod
        run: |
          python manage.py collectstatic --noinput

      - name: Upload static files to S3
        run: |
          aws s3 sync static/ s3://supportinbits-bucket/static/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
