# Generated by Django 4.2.23 on 2025-06-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='alt_img',
            field=models.CharField(default='alt imagen', max_length=255),
        ),
    ]
